### ISSUE TITLE
Erro ao rodar o projeto

### ISSUE THREAD

**Issue by luisangelorjr** [ThiagoWaishaupt/WebScraping#1]
Clonei o projeto aqui e parece que está em branco.
O que tá acontecendo?

Obrigado

**Comment by ThiagoWaishaupt** [comment]
Acabei de criar o repositório kkk vou codar ainda

**Comment by luisangelorjr** [comment]
Já passaram 4h. Tô esperando o código

**Comment by ThiagoWaishaupt** [comment]
Ta feito.
Se quiser fazer de outros sites, só criar outras funções la e ja era
